services:
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - cache
  db:
    container_name: db
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test1234
    networks:
      - database
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_LISTENER_NAMES: INSIDE
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093
      KAFKA_LISTENER_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      - message
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper
    restart: on-failure:5
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    networks:
      - message
  web:
    container_name: web
    image: demo
    restart: always
    ports:
      - "8080:8080"
    networks:
      - cache
      - database
      - message
    depends_on:
      - redis
      - db
      - kafka
      - zookeeper
networks:
  cache:
    driver: bridge
  database:
    driver: bridge
  message:
    driver: bridge