services:
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - cache
  db:
    container_name: db
    image: mysql
    # 舊版 password plugin 新版 caching_sha2_password 需要設置 allowPublicKeyRetrieval=true
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test1234
    networks:
      - database
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAMES: INSIDE
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093
      KAFKA_LISTENER_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      - message
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
#  control-center:
#    image: confluentinc/cp-enterprise-control-center
#    container_name: control-center
#    depends_on:
#      - zookeeper
#      - kafka
#    ports:
#      - "9021:9021"
#    environment:
#      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'localhsot:9092'
#      CONTROL_CENTER_ZOOKEEPER_CONNECT: 'localhost:2181'
#      CONTROL_CENTER_CONNECT_CLUSTER: 'connect:8083'
#      CONTROL_CENTER_KSQL_URL: "http://ksql-server:8088"
#      CONTROL_CENTER_KSQL_ADVERTISED_URL: "http://localhost:8088"
#      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
#      CONTROL_CENTER_REPLICATION_FACTOR: 1
#      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
#      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
#      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
#      PORT: 9021
#    networks:
#      - message
  web:
    container_name: web
    image: demo
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/?serverTimezone=Asia/Taipei&connectTimeout=2000&sessionVariables=character_set_connection=utf8mb4
      REDIS_HOST: redis
      REDIS_URL: redis://redis:6379
      KAFKA_BROKER: kafka
      KAFKA_URL: kafka://kafka:9093
    networks:
      - cache
      - database
      - message
    depends_on:
      - redis
      - db
      - kafka
      - zookeeper
#      - control-center
networks:
  cache:
    driver: bridge
  database:
    driver: bridge
  message:
    driver: bridge